spring: 
  # 国际化配置
  messages: 
    # 编码
    encoding: utf-8
    # 国际化资源文件路径
    basename: i18n/messages

server: 
  # 服务端口配置
  port: 8082
  servlet: 
    # 项目路径
    context-path: /ng-api/
    
# log 日志配置
logging: 
  config: classpath:./logbacks/logback-spring.xml
  level:
    dao: debug
    org: 
      mybatis: debug
  
# XSS防护
xss: 
  # 过滤开关
  enabled: true
  # 排除连接（用多个逗号分隔）
  excludes: /system/notice/*
  # 匹配链接（用多个逗号分隔）
  urlPatterns: /system/*,/monitor/*,/tool/*