spring:
  #数据库配置
  datasource:
    url: jdbc:postgresql://192.168.66.130:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: hmld
    
# mybatis 配置
mybatis: 
  typeAliasesPackage: com.github.hmld.**
  mapperLocations: classpath*:mybatis/mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml