# springboot 主配置文件
spring: 
  #是否启用热重启
  devtools.restart.enabled: true
  #开启切面变成（aop）
  aop.auto: true
  #多配置文件
  profiles: 
    active: 
      - system #系统配置
      - nextg #自定义配置
      - data #数据库配置