spring: 
  # 国际化配置
  messages: 
    # 编码
    encoding: utf-8
    # 国际化资源文件路径
    basename: i18n/messages
  freemarker: 
    cache: false # 关闭模板缓存
    charset: utf-8
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: true
    settings: 
      template_update_delay: 0 # 检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    template-loader-path: classpath:/templates/ # 模板路径
    suffix: .ftl # 模板后缀名称
    
server: 
  # 服务端口配置
  port: 8082
  #servlet: 
    # 项目路径
    #context-path: /ng-api/

# mybatis 配置
mybatis: 
  typeAliasesPackage: com.github.hmld.**
  mapperLocations: classpath*:mybatis/mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  supportMethodsArguments: true
  params: count=countSql

# log 日志配置
logging: 
  config: classpath:./logbacks/logback-spring.xml
  level:
    dao: debug
    org: 
      mybatis: debug
  
# token配置
token: 
  # token 标识
  header: Authorization
  # token 密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # token 有效期
  expireTime: 30

# XSS防护
xss: 
  # 过滤开关
  enabled: true
  # 排除连接（用多个逗号分隔）
  excludes: /system/notice/*
  # 匹配链接（用多个逗号分隔）
  urlPatterns: /system/*,/monitor/*,/tool/*